include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    document_ignores: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/firebase_options.dart"

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    library_private_types_in_public_api: false
    one_member_abstracts: false
    depend_on_referenced_packages: false
    use_setters_to_change_properties: false
