name: listicle
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^7.0.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: module/gen/assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: module/gen/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: module/gen/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
