name: listicle
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  get_it: ^8.0.3
  shared_preferences: ^2.5.2
  json_serializable: ^6.7.1
  equatable: ^2.0.7

  # Cache
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
